# Generated by Django 5.2.15 on 2026-09-14 09:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organization', '0010_site_chainage_end_km_site_chainage_start_km_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('name', models.CharField(max_length=200)),
                ('group_title', models.CharField(blank=True, help_text="Which generated group this activity belongs to on its parent (e.g. 'Abutment A1', 'Ground floor', 'S1 - Girder') - purely a display label, not a relation.", max_length=150)),
                ('group_subtitle', models.CharField(blank=True, max_length=200)),
                ('group_order', models.PositiveIntegerField(default=0)),
                ('row_order', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('TASK', 'Task (% complete)'), ('LENGTH', 'Length / quantity')], default='TASK', max_length=10)),
                ('unit', models.CharField(blank=True, help_text="Only meaningful for LENGTH activities (e.g. 'nos', 'm').", max_length=20)),
                ('total_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('done_qty', models.DecimalField(decimal_places=3, default=0, help_text='For a LENGTH activity: quantity done. For a TASK activity: percent done (0-100).', max_digits=12)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Taken Up'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('HOLD', 'Hold / Issue'), ('NOT_APPLICABLE', 'N/A')], db_index=True, default='NOT_STARTED', max_length=20)),
                ('is_doc', models.BooleanField(default=False, help_text='GAD / structural-drawing approval rows render as Approved/Submitted/Not submitted instead of a %/quantity.')),
                ('material_tracked', models.BooleanField(default=False)),
                ('material_status', models.CharField(blank=True, choices=[('NOT_ORDERED', 'Not Ordered'), ('PO_PLACED', 'PO Placed'), ('PARTLY_RECEIVED', 'Partly Received'), ('RECEIVED', 'Received At Site')], max_length=20, null=True)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'db_table': 'project_monitor_activity',
                'ordering': ['group_order', 'row_order'],
            },
        ),
        migrations.CreateModel(
            name='ActivityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_date', models.DateField()),
                ('text', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='project_monitor.activity')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Comment',
                'verbose_name_plural': 'Activity Comments',
                'db_table': 'project_monitor_activity_comment',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ActivityDateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_date', models.DateField()),
                ('meeting_date', models.DateField(help_text='Which review meeting set/revised this date.')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_entries', to='project_monitor.activity')),
            ],
            options={
                'verbose_name': 'Activity Date Entry',
                'verbose_name_plural': 'Activity Date Entries',
                'db_table': 'project_monitor_activity_date_entry',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StructureTypeDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description_template', models.CharField(blank=True, help_text="Auto-generated summary shown on every structure of this type - '{field_key}' placeholders are filled in from its config.", max_length=500)),
                ('config_schema', models.JSONField(blank=True, default=list)),
                ('group_templates', models.JSONField(blank=True, default=list)),
                ('include_approval_docs', models.BooleanField(default=True, help_text='Every generated structure gets a GAD approval + Structural drawing approval row up front, unless unticked.')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Structure Type',
                'verbose_name_plural': 'Structure Types',
                'db_table': 'project_monitor_structure_type',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('chainage_km', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text="The parametric inputs used to generate this structure's activities - display/audit only, never re-applied.")),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_monitor_structures', to='organization.site')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                ('structure_type', models.ForeignKey(help_text="PROTECTed, not cascaded: a structure type used by real structures can't be deleted out from under them.", on_delete=django.db.models.deletion.PROTECT, related_name='structures', to='project_monitor.structuretypedefinition')),
            ],
            options={
                'verbose_name': 'Structure',
                'verbose_name_plural': 'Structures',
                'db_table': 'project_monitor_structure',
                'ordering': [models.OrderBy(models.F('chainage_km'), nulls_last=True), 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['content_type', 'object_id'], name='pm_activity_parent_idx'),
        ),
    ]
