# Generated by Django 5.2.15 on 2026-09-14 10:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_site_chainage_end_km_site_chainage_start_km_and_more'),
        ('project_monitor', '0002_seed_builtin_structure_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station_label', models.CharField(blank=True, help_text="Which site/station within the project this building is at (e.g. 'Chunar station') - buildings are grouped by this label, purely a display grouping, not a relation.", max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('chainage_km', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_monitor_buildings', to='organization.site')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'db_table': 'project_monitor_building',
                'ordering': ['station_label', models.OrderBy(models.F('chainage_km'), nulls_last=True), 'created_at'],
            },
        ),
    ]
