# Generated by Django 5.2.15 on 2026-09-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_monitor', '0003_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='hindrance_actual_removal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='hindrance_expected_removal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='hindrance_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_hindrance',
            field=models.BooleanField(default=False, help_text='This activity (or the structure/building it belongs to) is currently blocked by Railways/Authority.'),
        ),
    ]
