# Generated by Django 5.2.15 on 2026-09-15 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_monitor', '0004_activity_hindrance_actual_removal_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='review_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Director or Project Manager sign-off on this row - a lightweight review record, not an edit gate. Re-reviewing overwrites the previous sign-off.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
