# Generated by Django 5.2.15 on 2026-09-15 15:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

DEFAULT_LIBRARY = [
    {"span_length_m": "12.20", "girder_type": "Composite girder", "display_order": 1},
    {"span_length_m": "18.30", "girder_type": "Composite girder", "display_order": 2},
    {"span_length_m": "24.40", "girder_type": "Welded plate girder", "display_order": 3},
    {"span_length_m": "30.50", "girder_type": "Welded plate girder", "display_order": 4},
    {"span_length_m": "45.70", "girder_type": "Open web girder", "display_order": 5},
    {"span_length_m": "61.00", "girder_type": "Open web girder", "display_order": 6},
    {"span_length_m": "76.20", "girder_type": "Open web girder", "display_order": 7},
]


def seed_default_library(apps, schema_editor):
    RdsoSpanLibraryEntry = apps.get_model(
        "project_monitor", "RdsoSpanLibraryEntry"
    )
    for payload in DEFAULT_LIBRARY:
        RdsoSpanLibraryEntry.objects.get_or_create(
            span_length_m=payload["span_length_m"],
            girder_type=payload["girder_type"],
            defaults=payload,
        )


def remove_default_library(apps, schema_editor):
    RdsoSpanLibraryEntry = apps.get_model(
        "project_monitor", "RdsoSpanLibraryEntry"
    )
    RdsoSpanLibraryEntry.objects.filter(
        girder_type__in={
            item["girder_type"] for item in DEFAULT_LIBRARY
        }
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_site_chainage_end_km_site_chainage_start_km_and_more'),
        ('project_monitor', '0005_activity_review_remarks_activity_reviewed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GirderJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('structure_kind', models.CharField(choices=[('MAJOR', 'Major Bridge'), ('ROB', 'ROB'), ('FOB', 'FOB')], max_length=10)),
                ('bridge_name', models.CharField(max_length=150)),
                ('chainage_km', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('girder_scope', models.CharField(choices=[('JNL', 'JNL (fabrication by vendor)'), ('RAILWAY', 'Railway supply - follow-up only')], max_length=10)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='girder_jobs', to='organization.site')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='girder_jobs', to='project_monitor.structure')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Girder Job',
                'verbose_name_plural': 'Girder Jobs',
                'db_table': 'project_monitor_girder_job',
                'ordering': [models.OrderBy(models.F('chainage_km'), nulls_last=True), 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GirderSpan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=50)),
                ('is_standard', models.BooleanField(default=False)),
                ('drawing_no', models.CharField(blank=True, max_length=100)),
                ('span_length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('girder_type', models.CharField(blank=True, max_length=100)),
                ('qty_mt', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('vendor', models.CharField(blank=True, max_length=150)),
                ('po_number', models.CharField(blank=True, max_length=100)),
                ('bearings_count', models.PositiveIntegerField(default=4)),
                ('expansion_joints_count', models.PositiveIntegerField(default=2)),
                ('row_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spans', to='project_monitor.girderjob')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Girder Span',
                'verbose_name_plural': 'Girder Spans',
                'db_table': 'project_monitor_girder_span',
                'ordering': ['row_order'],
            },
        ),
        migrations.CreateModel(
            name='RdsoSpanLibraryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('span_length_m', models.DecimalField(decimal_places=2, max_digits=6)),
                ('girder_type', models.CharField(max_length=100)),
                ('drawing_no', models.CharField(blank=True, max_length=100)),
                ('qty_per_span_mt', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RDSO Span Library Entry',
                'verbose_name_plural': 'RDSO Span Library Entries',
                'db_table': 'project_monitor_rdso_span_library_entry',
                'ordering': ['display_order', 'span_length_m'],
            },
        ),
        migrations.RunPython(
            seed_default_library, remove_default_library
        ),
    ]
