# Generated by Django 5.2.15 on 2026-09-16 07:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_site_project_value'),
        ('project_monitor', '0008_actionitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinearItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('unit', models.CharField(choices=[('M', 'Running metre (m)'), ('CUM', 'Cubic metre (cum)'), ('NOS', 'Numbers (nos)')], default='M', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linear_items', to='organization.site')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Linear Item',
                'verbose_name_plural': 'Linear Items',
                'db_table': 'project_monitor_linear_item',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProgressEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('from_chainage_km', models.DecimalField(decimal_places=3, max_digits=8)),
                ('to_chainage_km', models.DecimalField(decimal_places=3, max_digits=8)),
                ('qty', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('side', models.CharField(choices=[('BOTH', 'Both'), ('LHS', 'LHS'), ('RHS', 'RHS')], default='BOTH', max_length=10)),
                ('contractor', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('HOLD', 'Hold / Issue')], default='IN_PROGRESS', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('meeting_date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('linear_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='project_monitor.linearitem')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progress Entry',
                'verbose_name_plural': 'Progress Entries',
                'db_table': 'project_monitor_progress_entry',
                'ordering': ['-date', 'from_chainage_km'],
            },
        ),
        migrations.CreateModel(
            name='ScopePatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_chainage_km', models.DecimalField(decimal_places=3, max_digits=8)),
                ('to_chainage_km', models.DecimalField(decimal_places=3, max_digits=8)),
                ('side', models.CharField(choices=[('BOTH', 'Both'), ('LHS', 'LHS'), ('RHS', 'RHS')], default='BOTH', max_length=10)),
                ('qty', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('linear_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_patches', to='project_monitor.linearitem')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scope Patch',
                'verbose_name_plural': 'Scope Patches',
                'db_table': 'project_monitor_scope_patch',
                'ordering': ['from_chainage_km'],
            },
        ),
    ]
