# Generated by Django 5.2.15 on 2026-09-19 06:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_site_contract_no_site_opening_bill_date_and_more'),
        ('project_monitor', '0009_linearitem_progressentry_scopepatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DprItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_no', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('scope_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('concrete_per_unit', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('tmt_kg_per_unit', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('row_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpr_items', to='organization.site')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_monitor_dpr_item',
                'ordering': ['row_order', 'item_no', 'description'],
            },
        ),
        migrations.CreateModel(
            name='DprEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('agency', models.CharField(blank=True, max_length=150)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(choices=[('MANUAL_GRID', 'Daily grid'), ('DETAILED', 'Detailed entry'), ('EXCEL', 'Excel upload')], default='DETAILED', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='project_monitor.dpritem')),
            ],
            options={
                'db_table': 'project_monitor_dpr_entry',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSiteAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('DPR_BILLS', 'DPR & Bills entry')], default='DPR_BILLS', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_access', to='organization.site')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_monitor_site_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Monitor Site Access',
                'verbose_name_plural': 'Project Monitor Site Access',
                'db_table': 'project_monitor_site_access',
                'ordering': ['site__site_name', 'user__employee_id'],
            },
        ),
        migrations.CreateModel(
            name='RaBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_no', models.CharField(max_length=50)),
                ('bill_date', models.DateField()),
                ('received_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('received_on', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ra_bills', to='organization.site')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_monitor_ra_bill',
                'ordering': ['bill_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RaBillLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='project_monitor.rabill')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_lines', to='project_monitor.dpritem')),
            ],
            options={
                'db_table': 'project_monitor_ra_bill_line',
            },
        ),
        migrations.CreateModel(
            name='DprDayUnlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=300)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpr_day_unlocks', to='organization.site')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_monitor_dpr_day_unlock',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('site', 'date'), name='pm_dpr_unlock_site_date_uniq')],
            },
        ),
        migrations.AddConstraint(
            model_name='dpritem',
            constraint=models.UniqueConstraint(condition=models.Q(('item_no', ''), _negated=True), fields=('site', 'item_no'), name='pm_dpr_item_no_uniq'),
        ),
        migrations.AddIndex(
            model_name='dprentry',
            index=models.Index(fields=['item', 'date'], name='pm_dpr_entry_item_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='dprentry',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='pm_dpr_entry_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='projectsiteaccess',
            constraint=models.UniqueConstraint(fields=('site', 'user', 'role'), name='pm_site_access_uniq'),
        ),
        migrations.AddConstraint(
            model_name='rabill',
            constraint=models.UniqueConstraint(fields=('site', 'bill_no'), name='pm_ra_bill_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='rabillline',
            constraint=models.UniqueConstraint(fields=('bill', 'item'), name='pm_ra_bill_line_item_uniq'),
        ),
        migrations.AddConstraint(
            model_name='rabillline',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='pm_ra_bill_line_qty_positive'),
        ),
    ]
