# Generated by Django 5.2.15 on 2026-09-20 12:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_site_contract_no_site_opening_bill_date_and_more'),
        ('project_monitor', '0010_dpritem_dprentry_projectsiteaccess_rabill_rabillline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsiteaccess',
            name='role',
            field=models.CharField(choices=[('DPR_BILLS', 'DPR & Bills entry'), ('HR', 'HR entry')], default='DPR_BILLS', max_length=20),
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='organization.site')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_monitor_staff_member',
                'ordering': ['name', 'from_date'],
            },
        ),
        migrations.CreateModel(
            name='StaffDayOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_overrides', to='project_monitor.staffmember')),
            ],
            options={
                'db_table': 'project_monitor_staff_day_override',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LabourEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('category', models.CharField(max_length=100)),
                ('nos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('agency', models.CharField(blank=True, max_length=150)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('EXCEL', 'Excel')], default='MANUAL', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_entries', to='organization.site')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_monitor_labour_entry',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['site', 'date'], name='pm_labour_site_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('nos__gt', 0)), name='pm_labour_nos_positive'), models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='pm_labour_amount_non_negative')],
            },
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['site', 'from_date'], name='pm_staff_site_from_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffmember',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_salary__gte', 0)), name='pm_staff_salary_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='staffdayoverride',
            constraint=models.UniqueConstraint(fields=('staff', 'date'), name='pm_staff_override_uniq'),
        ),
        migrations.AddConstraint(
            model_name='staffdayoverride',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='pm_staff_override_non_negative'),
        ),
    ]
