# Generated by Django 5.2.15 on 2026-09-20 12:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_site_contract_no_site_opening_bill_date_and_more'),
        ('project_monitor', '0011_hr_labour_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsiteaccess',
            name='role',
            field=models.CharField(choices=[('DPR_BILLS', 'DPR & Bills entry'), ('HR', 'HR entry'), ('MACHINERY', 'Machinery entry')], default='DPR_BILLS', max_length=20),
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('reg_no', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(choices=[('MARKET', 'Market hire'), ('HO', 'In-house (HO)')], default='MARKET', max_length=10)),
                ('agency', models.CharField(blank=True, max_length=150)),
                ('hire_basis', models.CharField(choices=[('DAY', 'Per day'), ('HOUR', 'Per hour'), ('MONTH', 'Per month')], default='DAY', max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='organization.site')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_monitor_machine',
                'ordering': ['name', 'reg_no'],
            },
        ),
        migrations.CreateModel(
            name='FuelEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('litres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('EXCEL', 'Excel')], default='MANUAL', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to='organization.site')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuel_entries', to='project_monitor.machine')),
            ],
            options={
                'db_table': 'project_monitor_fuel_entry',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MachineUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('hire_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('maintenance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('other', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('EXCEL', 'Excel')], default='MANUAL', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='project_monitor.machine')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_monitor_machine_usage',
                'ordering': ['-date', 'machine__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.UniqueConstraint(fields=('site', 'name', 'reg_no'), name='pm_machine_site_name_reg_uniq'),
        ),
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0)), name='pm_machine_rate_non_negative'),
        ),
        migrations.AddIndex(
            model_name='fuelentry',
            index=models.Index(fields=['site', 'date'], name='pm_fuel_site_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='fuelentry',
            constraint=models.CheckConstraint(condition=models.Q(('litres__gt', 0), ('amount__gte', 0)), name='pm_fuel_positive'),
        ),
        migrations.AddConstraint(
            model_name='machineusage',
            constraint=models.UniqueConstraint(fields=('machine', 'date'), name='pm_machine_usage_day_uniq'),
        ),
        migrations.AddConstraint(
            model_name='machineusage',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gte', 0), ('hire_amount__gte', 0), ('maintenance__gte', 0), ('other__gte', 0)), name='pm_machine_usage_non_negative'),
        ),
    ]
