# Generated by Django 5.2.15 on 2026-09-21 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_site_contract_no_site_opening_bill_date_and_more'),
        ('project_monitor', '0012_machinery_fuel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rabill',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross value of an AMOUNT bill only.', max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='rabill',
            name='kind',
            field=models.CharField(choices=[('ITEMS', 'Item bill'), ('AMOUNT', 'Amount against project value')], default='ITEMS', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='rabill',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount__isnull', True), ('kind', 'ITEMS')), models.Q(('amount__gt', 0), ('amount__isnull', False), ('kind', 'AMOUNT')), _connector='OR'), name='pm_ra_bill_kind_amount'),
        ),
    ]
