# Generated by Django 5.2.15 on 2026-09-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_monitor', '0013_rabill_kind_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsiteaccess',
            name='role',
            field=models.CharField(choices=[('OVERVIEW', 'Project details & extensions'), ('STRUCTURES', 'Structures'), ('BUILDINGS', 'Buildings'), ('GIRDERS', 'Girders, bearings & EJ'), ('ACTION_ITEMS', 'Action items'), ('LINEAR_WORKS', 'Linear works'), ('DPR_BILLS', 'DPR & Bills'), ('HR', 'HR (labour & staff)'), ('MACHINERY', 'Machinery & fuel'), ('REPORTS', 'Reports')], default='DPR_BILLS', max_length=20),
        ),
    ]
