# Generated by Django 5.2.15 on 2026-09-22 11:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_site_contract_no_site_opening_bill_date_and_more'),
        ('project_monitor', '0016_backfill_starting_task_grants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcreteProduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('cum', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cement_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aggregate_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sand_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concrete_production', to='organization.site')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_monitor_concrete_production',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['site', 'date'], name='pm_concrete_prod_site_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('cum__gt', 0)), name='pm_concrete_prod_positive_cum')],
            },
        ),
        migrations.CreateModel(
            name='MaterialRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('CONCRETE', 'Concrete'), ('TMT', 'TMT steel')], max_length=20)),
                ('effective_from', models.DateField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_rates', to='organization.site')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_monitor_material_rate',
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['site', 'kind', 'effective_from'], name='pm_material_rate_idx')],
                'constraints': [models.UniqueConstraint(fields=('site', 'kind', 'effective_from'), name='pm_material_rate_unique'), models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='pm_material_rate_positive')],
            },
        ),
    ]
