# Generated by Django 5.2.15 on 2026-09-23 06:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_site_contract_no_site_opening_bill_date_and_more'),
        ('project_monitor', '0017_concreteproduction_materialrate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainageSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_chainage_km', models.DecimalField(decimal_places=3, max_digits=8)),
                ('to_chainage_km', models.DecimalField(decimal_places=3, max_digits=8)),
                ('vendor', models.CharField(blank=True, help_text='Who is working this stretch - optional, a stretch can go unassigned.', max_length=150)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chainage_segments', to='organization.site')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chainage Segment',
                'verbose_name_plural': 'Chainage Segments',
                'db_table': 'project_monitor_chainage_segment',
                'ordering': ['from_chainage_km'],
            },
        ),
    ]
