# Generated by Django 5.2.15 on 2026-09-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_monitor', '0019_remove_hr_machinery_grants'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='staff_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
