# Generated by Django 5.2.15 on 2026-09-25 12:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_boq_items_and_escalation'),
        ('project_monitor', '0020_staffmember_staff_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dpritem',
            name='authority_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='dpritem',
            name='is_heading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dpritem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='project_monitor.dpritem'),
        ),
        migrations.AddField(
            model_name='dpritem',
            name='tender_percent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
        migrations.CreateModel(
            name='RateEscalation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateField()),
                ('percent', models.DecimalField(decimal_places=3, max_digits=7)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_escalations', to='organization.site')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_monitor_rate_escalation',
                'ordering': ['effective_from'],
                'constraints': [models.UniqueConstraint(fields=('site', 'effective_from'), name='pm_rate_escalation_uniq')],
            },
        ),
    ]
