# Generated by Django 5.2.15 on 2026-09-25 14:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_monitor', '0021_boq_items_and_escalation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DprMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('nos', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('breadth', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('is_deduction', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('row_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='project_monitor.dpritem')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_monitor_dpr_measurement',
                'ordering': ['date', 'row_order'],
                'indexes': [models.Index(fields=['item', 'date'], name='pm_dpr_meas_item_date_idx')],
            },
        ),
    ]
