# Generated by Django 5.2.15 on 2026-09-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_monitor', '0022_dpr_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_custom',
            field=models.BooleanField(default=False, help_text="Added by hand through the + button, rather than generated from the parent's own template. Structure/Building edit reconciliation never touches a custom row - it keeps its group, position and history exactly as set, however many times the sheet's config is later regenerated."),
        ),
    ]
