# Generated by Django 5.2.15 on 2026-09-29 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_site_authority_escalation_percent_site_gst_percent'),
        ('project_monitor', '0024_girder_bridge_level_to_approvals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostingBoqItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_order', models.PositiveIntegerField(default=0)),
                ('item_no', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('qty', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('authority_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tender_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('our_cost_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('gst_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='project_monitor.costingboqitem')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costing_boq_items', to='organization.site')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_monitor_costing_boq_item',
                'ordering': ['row_order', 'item_no', 'description'],
            },
        ),
    ]
