# Generated by Django 5.2.15 on 2026-09-30 07:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_monitor', '0027_abutment_pier_names_and_fob_pile_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_type', models.CharField(choices=[('CHAINAGE', 'Chainage'), ('RAMP', 'Ramp')], default='CHAINAGE', max_length=10)),
                ('name', models.CharField(blank=True, help_text="e.g. 'Down line', 'R2' - optional, a structure with only one chainage/ramp may not need one.", max_length=100)),
                ('chainage_km', models.DecimalField(blank=True, decimal_places=3, help_text="The chainage/ramp's own numeric value, when it has one - optional, since a ramp may be identified purely by name.", max_digits=8, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='project_monitor.structure')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Structure Location',
                'verbose_name_plural': 'Structure Locations',
                'db_table': 'project_monitor_structure_location',
                'ordering': ['location_type', models.OrderBy(models.F('chainage_km'), nulls_last=True)],
            },
        ),
    ]
