# Generated by Django 5.2.15 on 2026-09-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_monitor', '0028_add_structure_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text="Hidden from this one sheet's UI - its history is kept and it can be shown again later. Hiding a generated row here never touches the structure type's own template or any other structure/building using it, since different sites often need a different subset of the same type's activities visible."),
        ),
    ]
