# Generated by Django 5.2.15 on 2026-10-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_monitor', '0030_activity_edit_access_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linearitem',
            name='unit',
            field=models.CharField(choices=[('M', 'Running metre (m)'), ('CUM', 'Cubic metre (cum)'), ('NOS', 'Numbers (nos)'), ('AREA', 'Area (sqm)')], default='M', max_length=10),
        ),
    ]
