# Generated by Django 5.2.15 on 2026-10-02 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_site_authority_escalation_percent_site_gst_percent'),
        ('project_monitor', '0031_add_area_linear_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuretypedefinition',
            name='distributed_sites',
            field=models.ManyToManyField(blank=True, help_text='Other sites an Admin/Director has given use-access to - they can pick this type on the Add-a-structure form, but cannot edit it. Only meaningful when owner_site is set; a global type is already usable everywhere.', related_name='distributed_structure_types', to='organization.site'),
        ),
        migrations.AddField(
            model_name='structuretypedefinition',
            name='owner_site',
            field=models.ForeignKey(blank=True, help_text="Blank = a global type, usable on every site (the built-ins, and anything an Admin/Director/HO adds directly). Set = a type a Project Manager/Incharge made for their own site - visible and usable only there, plus wherever an Admin/Director has distributed it. Only an Admin/Director (or the owning site's own Project Manager/Incharge) may edit it.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_structure_types', to='organization.site'),
        ),
    ]
