# Generated by Django 5.2.15 on 2026-07-31 04:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corrections', '0003_approvalworkflowpolicy_approvalworkflowlevel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('muted_event_types', models.JSONField(blank=True, default=list)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_preference',
                'ordering': ['user__employee_id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('REQUEST_SUBMITTED', 'Request Submitted'), ('APPROVAL_PENDING', 'Approval Pending'), ('REQUEST_APPROVED', 'Request Approved'), ('REQUEST_REJECTED', 'Request Rejected'), ('CLARIFICATION_REQUIRED', 'Clarification Required'), ('REQUEST_ASSIGNED', 'Request Assigned'), ('ASSIGNMENT_ACCEPTED', 'Assignment Accepted'), ('WORK_IN_PROGRESS', 'Work In Progress'), ('REQUEST_RESOLVED', 'Request Resolved'), ('CONFIRMATION_PENDING', 'Confirmation Pending'), ('REQUEST_REOPENED', 'Request Reopened'), ('SLA_WARNING', 'SLA Warning'), ('SLA_BREACH', 'SLA Breach')], db_index=True, max_length=40)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField(blank=True)),
                ('deep_link', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('delivered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('correction_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='corrections.correctionrequest')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='notif_recipient_read_idx'), models.Index(fields=['recipient', 'event_type'], name='notif_recipient_event_idx'), models.Index(fields=['correction_request', 'event_type'], name='notif_request_event_idx')],
            },
        ),
    ]
