# Generated by Django 5.2.15 on 2026-08-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationemaildelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('REQUEST_SUBMITTED', 'Request Submitted'), ('APPROVAL_PENDING', 'Approval Pending'), ('REQUEST_APPROVED', 'Request Approved'), ('REQUEST_REJECTED', 'Request Rejected'), ('CLARIFICATION_REQUIRED', 'Clarification Required'), ('REQUEST_ASSIGNED', 'Request Assigned'), ('ASSIGNMENT_ACCEPTED', 'Assignment Accepted'), ('WORK_IN_PROGRESS', 'Work In Progress'), ('REQUEST_RESOLVED', 'Request Resolved'), ('CONFIRMATION_PENDING', 'Confirmation Pending'), ('REQUEST_REOPENED', 'Request Reopened'), ('SLA_WARNING', 'SLA Warning'), ('SLA_BREACH', 'SLA Breach'), ('AUTO_CLOSE_REMINDER', 'Auto-Close Reminder'), ('REQUEST_AUTO_CLOSED', 'Request Auto-Closed')], db_index=True, max_length=40),
        ),
    ]
