# Generated by Django 5.2.15 on 2026-09-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('USER', 'Request Creator'), ('DIRECTOR', 'Director'), ('RESPONSIBLE_PERSON', 'Work Assignee'), ('EMPLOYEE', 'Employee'), ('STORE_HO', 'Store HO'), ('PROJECT_MANAGER', 'Project Manager'), ('PROJECT_INCHARGE', 'Project Incharge'), ('PROJECT_HO', 'Project Management HO'), ('HR_DEPARTMENT', 'HR Department'), ('MACHINERY_DEPARTMENT', 'Machinery Department')], db_index=True, default='USER', max_length=30),
        ),
    ]
