from django.urls import path

from apps.project_monitor.api.views import (
    ActivityReviewAPIView,
    ActivityUpdateAPIView,
    BuildingDetailAPIView,
    BuildingListCreateAPIView,
    BuildingReviewAPIView,
    GirderJobDetailAPIView,
    GirderJobListCreateAPIView,
    GirderJobReviewAPIView,
    GirderSpanUpdateAPIView,
    ProjectExtensionDetailAPIView,
    ProjectExtensionListCreateAPIView,
    ProjectOverviewAPIView,
    RdsoSpanLibraryEntryDetailAPIView,
    RdsoSpanLibraryEntryListCreateAPIView,
    StructureDetailAPIView,
    StructureListCreateAPIView,
    StructureReviewAPIView,
    StructureTypeDetailAPIView,
    StructureTypeListCreateAPIView,
)


app_name = "project-monitor-api"

urlpatterns = [
    path(
        "overview/",
        ProjectOverviewAPIView.as_view(),
        name="overview",
    ),
    path(
        "extensions/",
        ProjectExtensionListCreateAPIView.as_view(),
        name="extension-list",
    ),
    path(
        "extensions/<uuid:pk>/",
        ProjectExtensionDetailAPIView.as_view(),
        name="extension-detail",
    ),
    path(
        "structure-types/",
        StructureTypeListCreateAPIView.as_view(),
        name="structure-type-list",
    ),
    path(
        "structure-types/<uuid:pk>/",
        StructureTypeDetailAPIView.as_view(),
        name="structure-type-detail",
    ),
    path(
        "structures/",
        StructureListCreateAPIView.as_view(),
        name="structure-list",
    ),
    path(
        "structures/<uuid:pk>/",
        StructureDetailAPIView.as_view(),
        name="structure-detail",
    ),
    path(
        "structures/<uuid:pk>/review/",
        StructureReviewAPIView.as_view(),
        name="structure-review",
    ),
    path(
        "buildings/",
        BuildingListCreateAPIView.as_view(),
        name="building-list",
    ),
    path(
        "buildings/<uuid:pk>/",
        BuildingDetailAPIView.as_view(),
        name="building-detail",
    ),
    path(
        "buildings/<uuid:pk>/review/",
        BuildingReviewAPIView.as_view(),
        name="building-review",
    ),
    path(
        "rdso-span-library/",
        RdsoSpanLibraryEntryListCreateAPIView.as_view(),
        name="rdso-span-library-list",
    ),
    path(
        "rdso-span-library/<uuid:pk>/",
        RdsoSpanLibraryEntryDetailAPIView.as_view(),
        name="rdso-span-library-detail",
    ),
    path(
        "girder-jobs/",
        GirderJobListCreateAPIView.as_view(),
        name="girder-job-list",
    ),
    path(
        "girder-jobs/<uuid:pk>/",
        GirderJobDetailAPIView.as_view(),
        name="girder-job-detail",
    ),
    path(
        "girder-jobs/<uuid:pk>/review/",
        GirderJobReviewAPIView.as_view(),
        name="girder-job-review",
    ),
    path(
        "girder-spans/<uuid:pk>/",
        GirderSpanUpdateAPIView.as_view(),
        name="girder-span-update",
    ),
    path(
        "activities/<uuid:pk>/",
        ActivityUpdateAPIView.as_view(),
        name="activity-update",
    ),
    path(
        "activities/<uuid:pk>/review/",
        ActivityReviewAPIView.as_view(),
        name="activity-review",
    ),
]
