from django.urls import path

from apps.project_monitor.api.dashboard_views import (
    DueTrackerAPIView,
    OverdueCountsAPIView,
    ProjectDashboardAPIView,
)
from apps.project_monitor.api.dpr_views import (
    DprAccessAPIView,
    DprContractDetailsAPIView,
    DprEntryDetailAPIView,
    DprEntryListCreateAPIView,
    DprGridAPIView,
    DprItemDetailAPIView,
    DprItemImportAPIView,
    DprItemListCreateAPIView,
    DprTemplateAPIView,
    DprUnlockAPIView,
    DprUploadAPIView,
    FinancialReportAPIView,
    FinancialSummaryAPIView,
    RaBillDetailAPIView,
    RaBillListCreateAPIView,
)
from apps.project_monitor.api.hr_views import (
    HrAccessAPIView,
    HrLabourDetailAPIView,
    HrLabourListCreateAPIView,
    HrOverrideDetailAPIView,
    HrOverrideListCreateAPIView,
    HrStaffDetailAPIView,
    HrStaffListCreateAPIView,
    HrSummaryAPIView,
    HrTemplateAPIView,
    HrUploadAPIView,
)
from apps.project_monitor.api.machinery_views import (
    FuelDetailAPIView,
    FuelListCreateAPIView,
    MachineDetailAPIView,
    MachineListCreateAPIView,
    MachineryAccessAPIView,
    MachinerySummaryAPIView,
    MachineryTemplateAPIView,
    MachineryUploadAPIView,
    UsageDetailAPIView,
    UsageListCreateAPIView,
)
from apps.project_monitor.api.scope_views import (
    ProjectSitesAPIView,
    SiteScopeAPIView,
)
from apps.project_monitor.api.site_access_views import (
    SiteAccessDetailAPIView,
    SiteAccessListCreateAPIView,
    SiteAccessSetAPIView,
)
from apps.project_monitor.api.views import (
    ActionItemDetailAPIView,
    ActionItemListCreateAPIView,
    ActivityReviewAPIView,
    ActivityUpdateAPIView,
    BuildingDetailAPIView,
    BuildingListCreateAPIView,
    BuildingReviewAPIView,
    GirderJobDetailAPIView,
    GirderJobListCreateAPIView,
    GirderJobReviewAPIView,
    GirderSpanUpdateAPIView,
    LinearItemDetailAPIView,
    LinearItemListCreateAPIView,
    ProgressEntryDetailAPIView,
    ProgressEntryListCreateAPIView,
    ProjectExtensionDetailAPIView,
    ProjectExtensionListCreateAPIView,
    ProjectOverviewAPIView,
    RdsoSpanLibraryEntryDetailAPIView,
    RdsoSpanLibraryEntryListCreateAPIView,
    ScopePatchDetailAPIView,
    ScopePatchListCreateAPIView,
    StructureDetailAPIView,
    StructureListCreateAPIView,
    StructureReviewAPIView,
    StructureTypeDetailAPIView,
    StructureTypeListCreateAPIView,
)


app_name = "project-monitor-api"

urlpatterns = [
    path(
        "dpr/access/",
        DprAccessAPIView.as_view(),
        name="dpr-access",
    ),
    path(
        "dpr/contract/",
        DprContractDetailsAPIView.as_view(),
        name="dpr-contract",
    ),
    path(
        "dpr/items/",
        DprItemListCreateAPIView.as_view(),
        name="dpr-item-list",
    ),
    path(
        "dpr/items/import/",
        DprItemImportAPIView.as_view(),
        name="dpr-item-import",
    ),
    path(
        "dpr/items/<uuid:pk>/",
        DprItemDetailAPIView.as_view(),
        name="dpr-item-detail",
    ),
    path(
        "dpr/grid/",
        DprGridAPIView.as_view(),
        name="dpr-grid",
    ),
    path(
        "dpr/entries/",
        DprEntryListCreateAPIView.as_view(),
        name="dpr-entry-list",
    ),
    path(
        "dpr/entries/<uuid:pk>/",
        DprEntryDetailAPIView.as_view(),
        name="dpr-entry-detail",
    ),
    path(
        "dpr/template/",
        DprTemplateAPIView.as_view(),
        name="dpr-template",
    ),
    path(
        "dpr/upload/",
        DprUploadAPIView.as_view(),
        name="dpr-upload",
    ),
    path(
        "dpr/unlock/",
        DprUnlockAPIView.as_view(),
        name="dpr-unlock",
    ),
    path(
        "ra-bills/",
        RaBillListCreateAPIView.as_view(),
        name="ra-bill-list",
    ),
    path(
        "ra-bills/<uuid:pk>/",
        RaBillDetailAPIView.as_view(),
        name="ra-bill-detail",
    ),
    path(
        "financial-summary/",
        FinancialSummaryAPIView.as_view(),
        name="financial-summary",
    ),
    path(
        "financial-report/",
        FinancialReportAPIView.as_view(),
        name="financial-report",
    ),
    path(
        "hr/access/",
        HrAccessAPIView.as_view(),
        name="hr-access",
    ),
    path(
        "hr/summary/",
        HrSummaryAPIView.as_view(),
        name="hr-summary",
    ),
    path(
        "hr/labour/",
        HrLabourListCreateAPIView.as_view(),
        name="hr-labour-list",
    ),
    path(
        "hr/labour/<uuid:pk>/",
        HrLabourDetailAPIView.as_view(),
        name="hr-labour-detail",
    ),
    path(
        "hr/staff/",
        HrStaffListCreateAPIView.as_view(),
        name="hr-staff-list",
    ),
    path(
        "hr/staff/<uuid:pk>/",
        HrStaffDetailAPIView.as_view(),
        name="hr-staff-detail",
    ),
    path(
        "hr/overrides/",
        HrOverrideListCreateAPIView.as_view(),
        name="hr-override-list",
    ),
    path(
        "hr/overrides/<uuid:pk>/",
        HrOverrideDetailAPIView.as_view(),
        name="hr-override-detail",
    ),
    path(
        "hr/template/",
        HrTemplateAPIView.as_view(),
        name="hr-template",
    ),
    path(
        "hr/upload/",
        HrUploadAPIView.as_view(),
        name="hr-upload",
    ),
    path(
        "machinery/access/",
        MachineryAccessAPIView.as_view(),
        name="machinery-access",
    ),
    path(
        "machinery/summary/",
        MachinerySummaryAPIView.as_view(),
        name="machinery-summary",
    ),
    path(
        "machinery/machines/",
        MachineListCreateAPIView.as_view(),
        name="machinery-machine-list",
    ),
    path(
        "machinery/machines/<uuid:pk>/",
        MachineDetailAPIView.as_view(),
        name="machinery-machine-detail",
    ),
    path(
        "machinery/usage/",
        UsageListCreateAPIView.as_view(),
        name="machinery-usage-list",
    ),
    path(
        "machinery/usage/<uuid:pk>/",
        UsageDetailAPIView.as_view(),
        name="machinery-usage-detail",
    ),
    path(
        "machinery/fuel/",
        FuelListCreateAPIView.as_view(),
        name="machinery-fuel-list",
    ),
    path(
        "machinery/fuel/<uuid:pk>/",
        FuelDetailAPIView.as_view(),
        name="machinery-fuel-detail",
    ),
    path(
        "machinery/template/",
        MachineryTemplateAPIView.as_view(),
        name="machinery-template",
    ),
    path(
        "machinery/upload/",
        MachineryUploadAPIView.as_view(),
        name="machinery-upload",
    ),
    path(
        "sites/",
        ProjectSitesAPIView.as_view(),
        name="project-sites",
    ),
    path(
        "site-scope/",
        SiteScopeAPIView.as_view(),
        name="site-scope",
    ),
    path(
        "site-access/",
        SiteAccessListCreateAPIView.as_view(),
        name="site-access-list",
    ),
    path(
        "site-access/set/",
        SiteAccessSetAPIView.as_view(),
        name="site-access-set",
    ),
    path(
        "site-access/<uuid:pk>/",
        SiteAccessDetailAPIView.as_view(),
        name="site-access-detail",
    ),
    path(
        "dashboard/",
        ProjectDashboardAPIView.as_view(),
        name="dashboard",
    ),
    path(
        "due-tracker/",
        DueTrackerAPIView.as_view(),
        name="due-tracker",
    ),
    path(
        "overdue-counts/",
        OverdueCountsAPIView.as_view(),
        name="overdue-counts",
    ),
    path(
        "overview/",
        ProjectOverviewAPIView.as_view(),
        name="overview",
    ),
    path(
        "extensions/",
        ProjectExtensionListCreateAPIView.as_view(),
        name="extension-list",
    ),
    path(
        "extensions/<uuid:pk>/",
        ProjectExtensionDetailAPIView.as_view(),
        name="extension-detail",
    ),
    path(
        "structure-types/",
        StructureTypeListCreateAPIView.as_view(),
        name="structure-type-list",
    ),
    path(
        "structure-types/<uuid:pk>/",
        StructureTypeDetailAPIView.as_view(),
        name="structure-type-detail",
    ),
    path(
        "structures/",
        StructureListCreateAPIView.as_view(),
        name="structure-list",
    ),
    path(
        "structures/<uuid:pk>/",
        StructureDetailAPIView.as_view(),
        name="structure-detail",
    ),
    path(
        "structures/<uuid:pk>/review/",
        StructureReviewAPIView.as_view(),
        name="structure-review",
    ),
    path(
        "buildings/",
        BuildingListCreateAPIView.as_view(),
        name="building-list",
    ),
    path(
        "buildings/<uuid:pk>/",
        BuildingDetailAPIView.as_view(),
        name="building-detail",
    ),
    path(
        "buildings/<uuid:pk>/review/",
        BuildingReviewAPIView.as_view(),
        name="building-review",
    ),
    path(
        "rdso-span-library/",
        RdsoSpanLibraryEntryListCreateAPIView.as_view(),
        name="rdso-span-library-list",
    ),
    path(
        "rdso-span-library/<uuid:pk>/",
        RdsoSpanLibraryEntryDetailAPIView.as_view(),
        name="rdso-span-library-detail",
    ),
    path(
        "girder-jobs/",
        GirderJobListCreateAPIView.as_view(),
        name="girder-job-list",
    ),
    path(
        "girder-jobs/<uuid:pk>/",
        GirderJobDetailAPIView.as_view(),
        name="girder-job-detail",
    ),
    path(
        "girder-jobs/<uuid:pk>/review/",
        GirderJobReviewAPIView.as_view(),
        name="girder-job-review",
    ),
    path(
        "girder-spans/<uuid:pk>/",
        GirderSpanUpdateAPIView.as_view(),
        name="girder-span-update",
    ),
    path(
        "action-items/",
        ActionItemListCreateAPIView.as_view(),
        name="action-item-list",
    ),
    path(
        "action-items/<uuid:pk>/",
        ActionItemDetailAPIView.as_view(),
        name="action-item-detail",
    ),
    path(
        "linear-items/",
        LinearItemListCreateAPIView.as_view(),
        name="linear-item-list",
    ),
    path(
        "linear-items/<uuid:pk>/",
        LinearItemDetailAPIView.as_view(),
        name="linear-item-detail",
    ),
    path(
        "linear-items/<uuid:linear_item_pk>/scope-patches/",
        ScopePatchListCreateAPIView.as_view(),
        name="scope-patch-list",
    ),
    path(
        "scope-patches/<uuid:pk>/",
        ScopePatchDetailAPIView.as_view(),
        name="scope-patch-detail",
    ),
    path(
        "linear-items/<uuid:linear_item_pk>/progress-entries/",
        ProgressEntryListCreateAPIView.as_view(),
        name="progress-entry-list",
    ),
    path(
        "progress-entries/<uuid:pk>/",
        ProgressEntryDetailAPIView.as_view(),
        name="progress-entry-detail",
    ),
    path(
        "activities/<uuid:pk>/",
        ActivityUpdateAPIView.as_view(),
        name="activity-update",
    ),
    path(
        "activities/<uuid:pk>/review/",
        ActivityReviewAPIView.as_view(),
        name="activity-review",
    ),
]
