# Generated by Django 5.2.15 on 2026-07-22 07:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0007_auto_generated_master_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErpModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('module_code', models.CharField(blank=True, db_index=True, max_length=30, unique=True)),
                ('module_name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('departments', models.ManyToManyField(blank=True, related_name='erp_modules', to='organization.department')),
            ],
            options={
                'verbose_name': 'ERP Module',
                'verbose_name_plural': 'ERP Modules',
                'db_table': 'erp_module',
                'ordering': ['display_order', 'module_name'],
            },
        ),
        migrations.CreateModel(
            name='VoucherType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('voucher_code', models.CharField(blank=True, db_index=True, max_length=30)),
                ('voucher_name', models.CharField(max_length=150)),
                ('requires_voucher_number', models.BooleanField(default=True)),
                ('requires_voucher_date', models.BooleanField(default=True)),
                ('requires_amount', models.BooleanField(default=False)),
                ('requires_quantity', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_types', to='organization.department')),
                ('erp_module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_types', to='erp.erpmodule')),
            ],
            options={
                'verbose_name': 'Voucher Type',
                'verbose_name_plural': 'Voucher Types',
                'db_table': 'erp_voucher_type',
                'ordering': ['erp_module__module_name', 'voucher_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('work_type_code', models.CharField(blank=True, db_index=True, max_length=30, unique=True)),
                ('work_type_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('requires_approval', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Work Type',
                'verbose_name_plural': 'Work Types',
                'db_table': 'erp_work_type',
                'ordering': ['work_type_name'],
                'indexes': [models.Index(fields=['work_type_code', 'is_active'], name='erp_work_code_active_idx'), models.Index(fields=['requires_approval', 'is_active'], name='erp_work_approval_active_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='erpmodule',
            index=models.Index(fields=['module_code', 'is_active'], name='erp_module_code_active_idx'),
        ),
        migrations.AddIndex(
            model_name='erpmodule',
            index=models.Index(fields=['display_order', 'module_name'], name='erp_module_order_name_idx'),
        ),
        migrations.AddIndex(
            model_name='vouchertype',
            index=models.Index(fields=['erp_module', 'is_active'], name='erp_voucher_module_active_idx'),
        ),
        migrations.AddIndex(
            model_name='vouchertype',
            index=models.Index(fields=['department', 'is_active'], name='erp_voucher_dept_active_idx'),
        ),
        migrations.AddIndex(
            model_name='vouchertype',
            index=models.Index(fields=['voucher_code', 'is_active'], name='erp_voucher_code_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='vouchertype',
            constraint=models.UniqueConstraint(fields=('erp_module', 'voucher_code'), name='erp_voucher_module_code_uniq'),
        ),
    ]
