# Generated by Django 5.2.15 on 2026-07-22 08:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
        ('organization', '0007_auto_generated_master_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority_code', models.CharField(blank=True, db_index=True, max_length=30, unique=True)),
                ('priority_name', models.CharField(max_length=100, unique=True)),
                ('sla_duration_hours', models.PositiveIntegerField(default=24)),
                ('escalation_duration_hours', models.PositiveIntegerField(default=12)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Priority',
                'verbose_name_plural': 'Priorities',
                'db_table': 'erp_priority',
                'ordering': ['display_order', 'priority_name'],
                'indexes': [models.Index(fields=['priority_code', 'is_active'], name='erp_priority_code_active_idx'), models.Index(fields=['display_order', 'priority_name'], name='erp_priority_order_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReasonCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('reason_code', models.CharField(blank=True, db_index=True, max_length=30, unique=True)),
                ('reason_name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Reason Category',
                'verbose_name_plural': 'Reason Categories',
                'db_table': 'erp_reason_category',
                'ordering': ['display_order', 'reason_name'],
                'indexes': [models.Index(fields=['reason_code', 'is_active'], name='erp_reason_code_active_idx'), models.Index(fields=['display_order', 'reason_name'], name='erp_reason_order_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResponsiblePersonMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erp_responsible_person_mappings', to='organization.department')),
                ('erp_module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_person_mappings', to='erp.erpmodule')),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_person_mappings', to='erp.priority')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erp_responsible_person_mappings', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erp_responsible_person_mappings', to='organization.site')),
                ('voucher_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_person_mappings', to='erp.vouchertype')),
                ('work_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_person_mappings', to='erp.worktype')),
            ],
            options={
                'verbose_name': 'Responsible Person Mapping',
                'verbose_name_plural': 'Responsible Person Mappings',
                'db_table': 'erp_responsible_person_mapping',
                'ordering': ['display_order', 'erp_module__module_name', 'responsible_person__employee_id'],
                'indexes': [models.Index(fields=['erp_module', 'is_active'], name='erp_rpm_module_active_idx'), models.Index(fields=['voucher_type', 'is_active'], name='erp_rpm_voucher_active_idx'), models.Index(fields=['department', 'site', 'is_active'], name='erp_rpm_org_active_idx'), models.Index(fields=['work_type', 'priority', 'is_active'], name='erp_rpm_work_pri_active_idx'), models.Index(fields=['responsible_person', 'is_active'], name='erp_rpm_person_active_idx')],
            },
        ),
    ]
