# Generated by Django 5.2.15 on 2026-07-23 04:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_priority_reasoncategory_responsiblepersonmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFieldConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('field_key', models.CharField(blank=True, db_index=True, max_length=60)),
                ('field_label', models.CharField(max_length=150)),
                ('field_state', models.CharField(choices=[('REQUIRED', 'Required'), ('OPTIONAL', 'Optional'), ('HIDDEN', 'Hidden')], db_index=True, default='OPTIONAL', max_length=20)),
                ('help_text', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('erp_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_field_configurations', to='erp.erpmodule')),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_field_configurations', to='erp.priority')),
                ('voucher_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_field_configurations', to='erp.vouchertype')),
                ('work_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_field_configurations', to='erp.worktype')),
            ],
            options={
                'verbose_name': 'Request Field Configuration',
                'verbose_name_plural': 'Request Field Configurations',
                'db_table': 'erp_request_field_configuration',
                'ordering': ['display_order', 'field_label'],
                'indexes': [models.Index(fields=['field_key', 'is_active'], name='erp_rfc_key_active_idx'), models.Index(fields=['field_state', 'is_active'], name='erp_rfc_state_active_idx'), models.Index(fields=['erp_module', 'voucher_type', 'is_active'], name='erp_rfc_module_voucher_idx'), models.Index(fields=['work_type', 'priority', 'is_active'], name='erp_rfc_work_priority_idx')],
            },
        ),
    ]
