# Generated by Django 5.2.15 on 2026-08-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_requestfieldconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasoncategory',
            name='voucher_types',
            field=models.ManyToManyField(blank=True, help_text='Voucher types this reason applies to. Leave empty to make it available for every voucher type.', related_name='reason_categories', to='erp.vouchertype'),
        ),
    ]
