# Generated by Django 5.2.15 on 2026-07-21 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0006_remove_designation_org_desig_dept_code_uniq_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('employee_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('NOT_SPECIFIED', 'Not Specified')], db_index=True, default='NOT_SPECIFIED', max_length=20)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('PROBATION', 'Probation'), ('CONFIRMED', 'Confirmed'), ('CONTRACT', 'Contract'), ('NOTICE_PERIOD', 'Notice Period'), ('RELIEVED', 'Relieved'), ('TERMINATED', 'Terminated')], db_index=True, default='CONFIRMED', max_length=20)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('USER', 'User'), ('DIRECTOR', 'Director'), ('RESPONSIBLE_PERSON', 'Responsible Person')], db_index=True, default='USER', max_length=30)),
                ('erp_user_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('profile_photo', models.FileField(blank=True, upload_to='employees/profile_photos/')),
                ('last_working_date', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_profiles', to='organization.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_profiles', to='organization.designation')),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='employees.employeeprofile')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_profiles', to='organization.site')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Profile',
                'verbose_name_plural': 'Employee Profiles',
                'db_table': 'employees_employee_profile',
                'ordering': ['employee_id'],
                'indexes': [models.Index(fields=['employment_status', 'is_active'], name='emp_profile_status_active_idx'), models.Index(fields=['site', 'department', 'is_active'], name='emp_profile_org_active_idx'), models.Index(fields=['role', 'is_active'], name='emp_profile_role_active_idx')],
            },
        ),
    ]
