# Generated by Django 5.2.15 on 2026-08-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_generated_employee_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('USER', 'Request Creator'), ('DIRECTOR', 'Director'), ('RESPONSIBLE_PERSON', 'Work Assignee')], db_index=True, default='USER', max_length=30),
        ),
    ]
