# Generated by Django 5.2.15 on 2026-09-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employeeprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('USER', 'Request Creator'), ('DIRECTOR', 'Director'), ('RESPONSIBLE_PERSON', 'Work Assignee'), ('EMPLOYEE', 'Employee'), ('STORE_HO', 'Store HO'), ('PROJECT_MANAGER', 'Project Manager'), ('PROJECT_INCHARGE', 'Project Incharge')], db_index=True, default='USER', max_length=30),
        ),
    ]
