# Generated by Django 5.2.15 on 2026-07-23 06:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0003_requestfieldconfiguration'),
        ('organization', '0008_alter_directormapping_effective_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionRequestReferenceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(db_index=True, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Correction Request Reference Sequence',
                'verbose_name_plural': 'Correction Request Reference Sequences',
                'db_table': 'correction_request_reference_sequence',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=30, unique=True)),
                ('voucher_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('voucher_date', models.DateField(blank=True, null=True)),
                ('erp_email_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('requested_window_start', models.DateTimeField(blank=True, null=True)),
                ('requested_window_end', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('current_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REOPENED', 'Reopened'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30)),
                ('sla_deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('current_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_correction_requests', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_records', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction_requests', to='organization.department')),
                ('erp_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction_requests', to='erp.erpmodule')),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction_requests', to='erp.priority')),
                ('reason_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction_requests', to='erp.reasoncategory')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_requests', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction_requests', to='organization.site')),
                ('voucher_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction_requests', to='erp.vouchertype')),
                ('work_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction_requests', to='erp.worktype')),
            ],
            options={
                'verbose_name': 'Correction Request',
                'verbose_name_plural': 'Correction Requests',
                'db_table': 'correction_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requester', 'current_status'], name='corr_requester_status_idx'), models.Index(fields=['current_owner', 'current_status'], name='corr_owner_status_idx'), models.Index(fields=['voucher_type', 'voucher_number'], name='corr_voucher_lookup_idx'), models.Index(fields=['is_deleted', 'current_status'], name='corr_deleted_status_idx')],
            },
        ),
    ]
