# Generated by Django 5.2.15 on 2026-07-23 06:47

import apps.corrections.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='correctionrequest',
            name='duplicate_override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='correctionrequest',
            name='submitted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='CorrectionRequestAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to=apps.corrections.models.correction_attachment_upload_to)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('attachment_type', models.CharField(choices=[('SUPPORTING_DOCUMENT', 'Supporting Document'), ('EMAIL_SCREENSHOT', 'Email Screenshot')], db_index=True, default='SUPPORTING_DOCUMENT', max_length=30)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_records', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='corrections.correctionrequest')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Correction Request Attachment',
                'verbose_name_plural': 'Correction Request Attachments',
                'db_table': 'correction_request_attachment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request', 'is_deleted'], name='corr_attach_req_deleted_idx'), models.Index(fields=['uploaded_by', 'created_at'], name='corr_attach_user_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='CorrectionRequestTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('DRAFT_CREATED', 'Draft Created'), ('SUBMITTED', 'Submitted'), ('APPROVAL_ACTION', 'Approval Action'), ('ASSIGNED', 'Assigned'), ('STATUS_CHANGED', 'Status Changed'), ('COMMENT', 'Comment'), ('ATTACHMENT_ADDED', 'Attachment Added'), ('ATTACHMENT_DELETED', 'Attachment Deleted'), ('RESOLVED', 'Resolved'), ('REOPENED', 'Reopened'), ('CLOSED', 'Closed')], db_index=True, max_length=30)),
                ('from_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REOPENED', 'Reopened'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('to_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REOPENED', 'Reopened'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_timeline_entries', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeline_entries', to='corrections.correctionrequest')),
            ],
            options={
                'verbose_name': 'Correction Request Timeline',
                'verbose_name_plural': 'Correction Request Timelines',
                'db_table': 'correction_request_timeline',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['request', 'created_at'], name='corr_timeline_req_date_idx'), models.Index(fields=['event_type', 'created_at'], name='corr_timeline_event_date_idx')],
            },
        ),
    ]
