# Generated by Django 5.2.15 on 2026-07-28 04:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrections', '0002_correctionrequest_duplicate_override_reason_and_more'),
        ('erp', '0003_requestfieldconfiguration'),
        ('organization', '0008_alter_directormapping_effective_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflowPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('policy_name', models.CharField(db_index=True, max_length=150)),
                ('amount_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_records', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_workflow_policies', to='organization.department')),
                ('erp_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_workflow_policies', to='erp.erpmodule')),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_workflow_policies', to='erp.priority')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_workflow_policies', to='organization.site')),
                ('voucher_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_workflow_policies', to='erp.vouchertype')),
                ('work_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_workflow_policies', to='erp.worktype')),
            ],
            options={
                'verbose_name': 'Approval Workflow Policy',
                'verbose_name_plural': 'Approval Workflow Policies',
                'db_table': 'correction_approval_workflow_policy',
                'ordering': ['display_order', 'policy_name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflowLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('level_name', models.CharField(blank=True, max_length=120)),
                ('sequence', models.PositiveSmallIntegerField(db_index=True)),
                ('approver_type', models.CharField(choices=[('DEPARTMENT_HOD', 'Department HOD'), ('SITE_HOD', 'Site HOD'), ('DIRECTOR', 'Director'), ('ADMIN_FINAL', 'Admin Final Approval'), ('CUSTOM', 'Custom Approver')], db_index=True, max_length=30)),
                ('is_required', models.BooleanField(default=True)),
                ('sla_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('escalation_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('custom_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custom_approval_levels', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_records', to=settings.AUTH_USER_MODEL)),
                ('workflow_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_levels', to='corrections.approvalworkflowpolicy')),
            ],
            options={
                'verbose_name': 'Approval Workflow Level',
                'verbose_name_plural': 'Approval Workflow Levels',
                'db_table': 'correction_approval_workflow_level',
                'ordering': ['workflow_policy', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField(db_index=True)),
                ('level_name', models.CharField(blank=True, max_length=120)),
                ('approver_type', models.CharField(choices=[('DEPARTMENT_HOD', 'Department HOD'), ('SITE_HOD', 'Site HOD'), ('DIRECTOR', 'Director'), ('ADMIN_FINAL', 'Admin Final Approval'), ('CUSTOM', 'Custom Approver')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned For Clarification'), ('DELEGATED', 'Delegated'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=30)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('escalates_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('policy_name_snapshot', models.CharField(blank=True, max_length=150)),
                ('approver_employee_id_snapshot', models.CharField(blank=True, max_length=30)),
                ('approver_name_snapshot', models.CharField(blank=True, max_length=150)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_approval_steps', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_steps', to='corrections.correctionrequest')),
                ('workflow_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_step_snapshots', to='corrections.approvalworkflowpolicy')),
            ],
            options={
                'verbose_name': 'Correction Approval Step',
                'verbose_name_plural': 'Correction Approval Steps',
                'db_table': 'correction_approval_step',
                'ordering': ['request', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='approvalworkflowpolicy',
            index=models.Index(fields=['is_active', 'display_order'], name='corr_awp_active_order_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflowpolicy',
            index=models.Index(fields=['site', 'department', 'is_active'], name='corr_awp_org_active_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflowpolicy',
            index=models.Index(fields=['erp_module', 'voucher_type', 'is_active'], name='corr_awp_erp_active_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflowpolicy',
            index=models.Index(fields=['work_type', 'priority', 'is_active'], name='corr_awp_work_active_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflowlevel',
            index=models.Index(fields=['workflow_policy', 'is_deleted', 'sequence'], name='corr_awl_policy_order_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflowlevel',
            index=models.Index(fields=['approver_type', 'is_deleted'], name='corr_awl_type_deleted_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalworkflowlevel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('workflow_policy', 'sequence'), name='corr_awl_policy_sequence_uniq'),
        ),
        migrations.AddIndex(
            model_name='correctionapprovalstep',
            index=models.Index(fields=['request', 'status'], name='corr_step_request_status_idx'),
        ),
        migrations.AddIndex(
            model_name='correctionapprovalstep',
            index=models.Index(fields=['approver', 'status'], name='corr_step_approver_status_idx'),
        ),
        migrations.AddIndex(
            model_name='correctionapprovalstep',
            index=models.Index(fields=['request', 'is_current'], name='corr_step_request_current_idx'),
        ),
        migrations.AddConstraint(
            model_name='correctionapprovalstep',
            constraint=models.UniqueConstraint(fields=('request', 'sequence'), name='corr_approval_step_request_sequence_uniq'),
        ),
    ]
