# Generated by Django 5.2.15 on 2026-08-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrections', '0003_approvalworkflowpolicy_approvalworkflowlevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctionrequest',
            name='current_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('RESOLVED', 'Resolved'), ('REOPENED', 'Reopened'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='correctionrequesttimeline',
            name='from_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('RESOLVED', 'Resolved'), ('REOPENED', 'Reopened'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=30),
        ),
        migrations.AlterField(
            model_name='correctionrequesttimeline',
            name='to_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('RESOLVED', 'Resolved'), ('REOPENED', 'Reopened'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=30),
        ),
    ]
