# Generated by Django 5.2.15 on 2026-08-12 09:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrections', '0004_alter_correctionrequest_current_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionRequestResolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('erp_action_completed', models.TextField()),
                ('completion_date', models.DateField()),
                ('erp_reference', models.CharField(blank=True, max_length=100)),
                ('access_window_start_used', models.DateTimeField(blank=True, null=True)),
                ('access_window_end_used', models.DateTimeField(blank=True, null=True)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('final_comments', models.TextField(blank=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolutions', to='corrections.correctionrequest')),
                ('resolved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_resolutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Correction Request Resolution',
                'verbose_name_plural': 'Correction Request Resolutions',
                'db_table': 'correction_request_resolution',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request', 'created_at'], name='corr_resolution_req_date_idx')],
            },
        ),
    ]
