# Generated by Django 5.2.15 on 2026-08-13 07:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrections', '0005_correctionrequestresolution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionAutoCloseSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('auto_close_after_days', models.PositiveIntegerField(default=7)),
                ('reminder_before_days', models.PositiveIntegerField(default=2)),
                ('exclude_critical_priority', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Auto-Close Settings',
                'verbose_name_plural': 'Auto-Close Settings',
                'db_table': 'correction_auto_close_settings',
            },
        ),
        migrations.AddField(
            model_name='correctionrequest',
            name='closed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='correctionrequest',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_correction_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correctionrequest',
            name='closure_type',
            field=models.CharField(blank=True, choices=[('CONFIRMED', 'Confirmed By Requester'), ('AUTO_CLOSED', 'Auto-Closed')], max_length=20),
        ),
        migrations.AddField(
            model_name='correctionrequest',
            name='final_sla_result',
            field=models.CharField(blank=True, choices=[('MET', 'Met'), ('BREACHED', 'Breached'), ('NOT_APPLICABLE', 'Not Applicable')], max_length=20),
        ),
        migrations.AddField(
            model_name='correctionrequest',
            name='resolution_duration_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
