# Generated by Django 5.2.15 on 2026-08-14 06:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrections', '0006_correctionautoclosesettings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='correctionrequest',
            name='ho_work_authority',
            field=models.ForeignKey(blank=True, help_text='HO person whose action caused this issue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ho_work_authority_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correctionrequest',
            name='root_cause_person',
            field=models.ForeignKey(blank=True, help_text='Main person responsible for the issue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_cause_correction_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correctionrequest',
            name='site_work_authority',
            field=models.ForeignKey(blank=True, help_text='Site person whose action caused this issue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_work_authority_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CorrectionWorkAuthorityUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authority_type', models.CharField(choices=[('HO', 'HO Work Authority'), ('SITE', 'Site Work Authority')], db_index=True, max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_authority_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Authority User',
                'verbose_name_plural': 'Work Authority Users',
                'db_table': 'correction_work_authority_user',
                'ordering': ['authority_type', 'user__employee_id'],
                'indexes': [models.Index(fields=['authority_type', 'is_active'], name='corr_work_auth_type_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('authority_type', 'user'), name='corr_work_authority_type_user_uniq')],
            },
        ),
    ]
