# Generated by Django 5.2.15 on 2026-08-14 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corrections', '0007_correctionrequest_ho_work_authority_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CorrectionWorkAuthorityUser',
        ),
    ]
