# Generated by Django 5.2.15 on 2026-08-14 10:55
# Hand-edited: ho_work_authority / site_work_authority /
# root_cause_person move from User FKs to EmployeeProfile FKs (these
# people no longer need a login account). Existing values are User
# ids; they are remapped to the matching EmployeeProfile id (via
# EmployeeProfile.user_id) before the new foreign key constraints
# are added, so no data is lost for anyone who already has both a
# User account and an EmployeeProfile. Any value that cannot be
# matched is cleared rather than left dangling.

import django.db.models.deletion
from django.db import migrations, models


REMAP_SQL = """
    UPDATE correction_request AS request
    SET {column} = profile.id
    FROM employees_employee_profile AS profile
    WHERE profile.user_id = request.{column}
      AND request.{column} IS NOT NULL;

    UPDATE correction_request
    SET {column} = NULL
    WHERE {column} IS NOT NULL
      AND {column} NOT IN (
          SELECT id FROM employees_employee_profile
      );
"""

REVERSE_REMAP_SQL = """
    UPDATE correction_request AS request
    SET {column} = profile.user_id
    FROM employees_employee_profile AS profile
    WHERE profile.id = request.{column}
      AND request.{column} IS NOT NULL;

    UPDATE correction_request
    SET {column} = NULL
    WHERE {column} IS NOT NULL
      AND {column} NOT IN (
          SELECT id FROM authentication_user
      );
"""


class Migration(migrations.Migration):

    dependencies = [
        ('corrections', '0008_delete_correctionworkauthorityuser'),
        ('employees', '0005_alter_employeeprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctionrequest',
            name='ho_work_authority',
            field=models.UUIDField(
                blank=True,
                null=True,
                db_column='ho_work_authority_id',
            ),
        ),
        migrations.AlterField(
            model_name='correctionrequest',
            name='site_work_authority',
            field=models.UUIDField(
                blank=True,
                null=True,
                db_column='site_work_authority_id',
            ),
        ),
        migrations.AlterField(
            model_name='correctionrequest',
            name='root_cause_person',
            field=models.UUIDField(
                blank=True,
                null=True,
                db_column='root_cause_person_id',
            ),
        ),
        migrations.RunSQL(
            sql=REMAP_SQL.format(
                column='ho_work_authority_id'
            )
            + REMAP_SQL.format(
                column='site_work_authority_id'
            )
            + REMAP_SQL.format(
                column='root_cause_person_id'
            ),
            reverse_sql=REVERSE_REMAP_SQL.format(
                column='ho_work_authority_id'
            )
            + REVERSE_REMAP_SQL.format(
                column='site_work_authority_id'
            )
            + REVERSE_REMAP_SQL.format(
                column='root_cause_person_id'
            ),
        ),
        migrations.AlterField(
            model_name='correctionrequest',
            name='ho_work_authority',
            field=models.ForeignKey(
                blank=True,
                help_text='HO person whose action caused this issue.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='ho_work_authority_requests',
                to='employees.employeeprofile',
            ),
        ),
        migrations.AlterField(
            model_name='correctionrequest',
            name='root_cause_person',
            field=models.ForeignKey(
                blank=True,
                help_text='Main person responsible for the issue.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='root_cause_correction_requests',
                to='employees.employeeprofile',
            ),
        ),
        migrations.AlterField(
            model_name='correctionrequest',
            name='site_work_authority',
            field=models.ForeignKey(
                blank=True,
                help_text='Site person whose action caused this issue.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='site_work_authority_requests',
                to='employees.employeeprofile',
            ),
        ),
    ]
