# Generated by Django 5.2.15 on 2026-08-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrections', '0009_alter_correctionrequest_ho_work_authority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctionapprovalstep',
            name='is_sequential_route',
            field=models.BooleanField(default=False, help_text='True when this step is part of a policy-configured multi-level chain (one step active at a time, approve_step advances to the next sequence). False for the default Director-then-Admin route, where every step is current at once and the first decision wins. Set once at snapshot time - do not infer this from other state.'),
        ),
    ]
