# Generated by Django 5.2.15 on 2026-07-18 08:19

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('company_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('company_name', models.CharField(max_length=150)),
                ('registered_name', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('time_zone', models.CharField(default=django.utils.timezone.get_default_timezone_name, max_length=64)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'organization_company',
                'ordering': ['company_name'],
                'indexes': [models.Index(fields=['company_code', 'is_active'], name='org_company_code_active_idx'), models.Index(fields=['company_name'], name='org_company_name_idx')],
            },
        ),
    ]
