# Generated by Django 5.2.15 on 2026-07-18 08:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('site_code', models.CharField(db_index=True, max_length=30)),
                ('site_name', models.CharField(max_length=150)),
                ('project_name', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cost_centre', models.CharField(blank=True, max_length=50)),
                ('erp_site_code', models.CharField(blank=True, max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='organization.company')),
                ('site_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_sites', to=settings.AUTH_USER_MODEL)),
                ('site_hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'db_table': 'organization_site',
                'ordering': ['site_name'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='org_site_company_active_idx'), models.Index(fields=['site_code', 'is_active'], name='org_site_code_active_idx'), models.Index(fields=['state', 'district'], name='org_site_location_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'site_code'), name='org_site_company_code_uniq')],
            },
        ),
    ]
