# Generated by Django 5.2.15 on 2026-07-18 09:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_site'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('department_code', models.CharField(db_index=True, max_length=30)),
                ('department_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='organization.company')),
                ('department_hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'organization_department',
                'ordering': ['display_order', 'department_name'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='org_dept_company_active_idx'), models.Index(fields=['department_code', 'is_active'], name='org_dept_code_active_idx'), models.Index(fields=['display_order', 'department_name'], name='org_dept_display_name_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'department_code'), name='org_dept_company_code_uniq')],
            },
        ),
    ]
