# Generated by Django 5.2.15 on 2026-07-18 09:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('designation_code', models.CharField(db_index=True, max_length=30)),
                ('designation_name', models.CharField(max_length=150)),
                ('level', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designations', to='organization.department')),
            ],
            options={
                'verbose_name': 'Designation',
                'verbose_name_plural': 'Designations',
                'db_table': 'organization_designation',
                'ordering': ['level', 'designation_name'],
                'indexes': [models.Index(fields=['department', 'is_active'], name='org_desig_dept_active_idx'), models.Index(fields=['designation_code', 'is_active'], name='org_desig_code_active_idx'), models.Index(fields=['level', 'designation_name'], name='org_desig_level_name_idx')],
                'constraints': [models.UniqueConstraint(fields=('department', 'designation_code'), name='org_desig_dept_code_uniq')],
            },
        ),
    ]
