# Generated by Django 5.2.15 on 2026-07-18 12:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_designation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('authority_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('BACKUP', 'Backup')], db_index=True, default='PRIMARY', max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='director_mappings', to='organization.department')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='director_authority_mappings', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='director_mappings', to='organization.site')),
            ],
            options={
                'verbose_name': 'Director Mapping',
                'verbose_name_plural': 'Director Mappings',
                'db_table': 'organization_director_mapping',
                'ordering': ['director__employee_id', '-effective_from'],
                'indexes': [models.Index(fields=['director', 'is_active'], name='org_dir_director_active_idx'), models.Index(fields=['site', 'is_active'], name='org_dir_site_active_idx'), models.Index(fields=['department', 'is_active'], name='org_dir_dept_active_idx'), models.Index(fields=['authority_type', 'is_active'], name='org_dir_auth_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('director', 'site', 'department', 'authority_type', 'effective_from'), name='org_director_mapping_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ReportingManagerMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reporting_manager_mappings', to='organization.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reporting_relations', to=settings.AUTH_USER_MODEL)),
                ('reporting_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_report_relations', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reporting_manager_mappings', to='organization.site')),
            ],
            options={
                'verbose_name': 'Reporting Manager Mapping',
                'verbose_name_plural': 'Reporting Manager Mappings',
                'db_table': 'organization_reporting_manager_mapping',
                'ordering': ['employee__employee_id', '-effective_from'],
                'indexes': [models.Index(fields=['employee', 'is_active'], name='org_rm_employee_active_idx'), models.Index(fields=['reporting_manager', 'is_active'], name='org_rm_manager_active_idx'), models.Index(fields=['site', 'department', 'is_active'], name='org_rm_context_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'reporting_manager', 'site', 'department', 'effective_from'), name='org_reporting_mapping_uniq')],
            },
        ),
        migrations.CreateModel(
            name='SiteDepartmentMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_date', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_mappings', to='organization.department')),
                ('department_hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_site_hod_mappings', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_mappings', to='organization.site')),
                ('site_hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_department_hod_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Department Mapping',
                'verbose_name_plural': 'Site Department Mappings',
                'db_table': 'organization_site_department_mapping',
                'ordering': ['site__site_name', 'department__department_name', '-effective_date'],
                'indexes': [models.Index(fields=['site', 'is_active'], name='org_sdm_site_active_idx'), models.Index(fields=['department', 'is_active'], name='org_sdm_dept_active_idx'), models.Index(fields=['effective_date'], name='org_sdm_eff_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('site', 'department', 'effective_date'), name='org_site_dept_eff_date_uniq'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('site', 'department'), name='org_active_site_dept_uniq')],
            },
        ),
    ]
