# Generated by Django 5.2.15 on 2026-07-21 06:08

from django.db import migrations, models


def deduplicate_designation_codes(apps, schema_editor):
    Designation = apps.get_model(
        "organization",
        "Designation",
    )

    seen_codes = set()

    for designation in Designation.objects.order_by(
        "designation_code",
        "level",
        "designation_name",
        "created_at",
        "id",
    ):
        if designation.designation_code in seen_codes:
            designation.delete()
            continue

        seen_codes.add(designation.designation_code)


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_directormapping_reportingmanagermapping_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='designation',
            name='org_desig_dept_code_uniq',
        ),
        migrations.RemoveIndex(
            model_name='designation',
            name='org_desig_dept_active_idx',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='department',
        ),
        migrations.RunPython(
            deduplicate_designation_codes,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='designation',
            name='designation_code',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
