# Generated by Django 5.2.15 on 2026-07-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_generated_master_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directormapping',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
