# Generated by Django 5.2.15 on 2026-08-14 10:54
# Hand-edited: Site.site_hod moves from a User FK to an
# EmployeeProfile FK (Site PM no longer needs a login account).
# Existing values are User ids; they are remapped to the matching
# EmployeeProfile id (via EmployeeProfile.user_id) before the new
# foreign key constraint is added, so no data is lost for any site
# PM that already has both a User account and an EmployeeProfile.
# Any value that cannot be matched (e.g. the User has no linked
# EmployeeProfile) is cleared rather than left dangling.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employeeprofile_role'),
        ('organization', '0008_alter_directormapping_effective_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_hod',
            field=models.UUIDField(
                blank=True,
                null=True,
                db_column='site_hod_id',
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE organization_site AS site
                SET site_hod_id = profile.id
                FROM employees_employee_profile AS profile
                WHERE profile.user_id = site.site_hod_id
                  AND site.site_hod_id IS NOT NULL;

                UPDATE organization_site
                SET site_hod_id = NULL
                WHERE site_hod_id IS NOT NULL
                  AND site_hod_id NOT IN (
                      SELECT id FROM employees_employee_profile
                  );
            """,
            reverse_sql="""
                UPDATE organization_site AS site
                SET site_hod_id = profile.user_id
                FROM employees_employee_profile AS profile
                WHERE profile.id = site.site_hod_id
                  AND site.site_hod_id IS NOT NULL;

                UPDATE organization_site
                SET site_hod_id = NULL
                WHERE site_hod_id IS NOT NULL
                  AND site_hod_id NOT IN (
                      SELECT id FROM authentication_user
                  );
            """,
        ),
        migrations.AlterField(
            model_name='site',
            name='site_hod',
            field=models.ForeignKey(
                blank=True,
                help_text='Site PM. Not restricted to employees with a login account.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='hod_sites',
                to='employees.employeeprofile',
            ),
        ),
    ]
