# Generated by Django 5.2.15 on 2026-09-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_alter_site_site_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='chainage_end_km',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Project Monitor: chainage where this project/site's works end, in km.", max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='chainage_start_km',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Project Monitor: chainage where this project/site's works begin, in km.", max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='client_or_section',
            field=models.CharField(blank=True, help_text="Project Monitor: the client / railway section this project reports to, e.g. 'NCR Prayagraj'.", max_length=150),
        ),
    ]
