# Generated by Django 5.2.15 on 2026-09-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_site_chainage_end_km_site_chainage_start_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='project_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Project Monitor: the awarded contract value for this project, in ₹.', max_digits=16, null=True),
        ),
    ]
