# Generated by Django 5.2.15 on 2026-09-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_site_project_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='contract_no',
            field=models.CharField(blank=True, help_text='Project Monitor finance: contract / LOA number.', max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='opening_bill_date',
            field=models.DateField(blank=True, help_text='Project Monitor finance: date of the last RA bill raised before this system.', null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='opening_bill_no',
            field=models.CharField(blank=True, help_text='Project Monitor finance: number of the last RA bill raised before this system.', max_length=50),
        ),
        migrations.AddField(
            model_name='site',
            name='opening_billed_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Project Monitor finance: gross value already billed BEFORE RA bills were recorded in this system, in ₹.', max_digits=16),
        ),
        migrations.AddField(
            model_name='site',
            name='varied_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Project Monitor finance: contract value as per the latest variation, in ₹. Falls back to the awarded value when blank.', max_digits=16, null=True),
        ),
    ]
