# Generated by Django 5.2.15 on 2026-09-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_site_contract_no_site_opening_bill_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='tender_percent',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Project Monitor finance: the tender percentage over (+) or under (-) the authority rate, applied to every BOQ item that has an authority rate and no percentage of its own.', max_digits=7, null=True),
        ),
    ]
