# Generated by Django 5.2.15 on 2026-09-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_boq_items_and_escalation'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='authority_escalation_percent',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Project Monitor Costing: a departmental escalation over every BOQ item's authority rate, applied before the tender percentage - e.g. the Railway revising its schedule of rates.", max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='gst_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Project Monitor Costing: the GST rate shown on top of a BOQ item's bid value, unless the item overrides it. Profit/loss is always worked out GST-exclusive.", max_digits=5, null=True),
        ),
    ]
