# Generated by Django 5.2.15 on 2026-08-24 07:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0009_alter_site_site_hod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('category_code', models.CharField(blank=True, db_index=True, max_length=30, unique=True)),
                ('category_name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Item Category',
                'verbose_name_plural': 'Item Categories',
                'db_table': 'reconciliation_item_category',
                'ordering': ['display_order', 'category_name'],
                'indexes': [models.Index(fields=['category_code', 'is_active'], name='reco_cat_code_active_idx'), models.Index(fields=['display_order', 'category_name'], name='reco_cat_order_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('item_code', models.CharField(blank=True, db_index=True, max_length=30)),
                ('item_name', models.CharField(max_length=150)),
                ('reconciliation_type', models.CharField(choices=[('NORM_BASED', 'Norm Based'), ('DIRECT_COUNT', 'Direct Count')], db_index=True, max_length=20)),
                ('uom', models.CharField(help_text='Unit of measure, e.g. MT, NOS, LTR.', max_length=20)),
                ('erp_item_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='reconciliation.itemcategory')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'reconciliation_item',
                'ordering': ['category__display_order', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='ItemStandard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('mix_ratio', models.DecimalField(blank=True, decimal_places=6, help_text='Required for norm-based items; unused for direct-count items.', max_digits=10, null=True)),
                ('effective_from', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_standards', to='reconciliation.item')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item Standard (Company Default)',
                'verbose_name_plural': 'Item Standards (Company Defaults)',
                'db_table': 'reconciliation_item_standard',
                'ordering': ['item__item_name', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='SiteItemConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('mix_ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('effective_from', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_configs', to='reconciliation.item')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_item_configs', to='organization.site')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Item Configuration',
                'verbose_name_plural': 'Site Item Configurations',
                'db_table': 'reconciliation_site_item_config',
                'ordering': ['site__site_name', 'item__item_name', '-effective_from'],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category', 'is_active'], name='reco_item_cat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['reconciliation_type', 'is_active'], name='reco_item_type_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('category', 'item_code'), name='reco_item_category_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='itemstandard',
            index=models.Index(fields=['item', 'is_active'], name='reco_std_item_active_idx'),
        ),
        migrations.AddIndex(
            model_name='itemstandard',
            index=models.Index(fields=['effective_from'], name='reco_std_eff_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemstandard',
            constraint=models.UniqueConstraint(fields=('item', 'effective_from'), name='reco_item_standard_item_date_uniq'),
        ),
        migrations.AddIndex(
            model_name='siteitemconfig',
            index=models.Index(fields=['site', 'item', 'is_active'], name='reco_site_item_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='siteitemconfig',
            constraint=models.UniqueConstraint(fields=('item', 'site', 'effective_from'), name='reco_site_item_date_uniq'),
        ),
        migrations.AddConstraint(
            model_name='siteitemconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('item', 'site'), name='reco_site_item_active_uniq'),
        ),
    ]
