# Generated by Django 5.2.15 on 2026-08-24 09:40

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_alter_site_site_hod'),
        ('reconciliation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationToleranceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_tolerance_percentage', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5)),
                ('watch_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Variance above tolerance x this multiplier is Over Tolerance; below it is Watch.', max_digits=4)),
            ],
            options={
                'verbose_name': 'Tolerance Settings',
                'verbose_name_plural': 'Tolerance Settings',
                'db_table': 'reconciliation_tolerance_settings',
            },
        ),
        migrations.CreateModel(
            name='ReconciliationEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opening_stock', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('receipts', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('closing_stock', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('book_stock', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('physical_count', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('theoretical_or_book_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('variance_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('variance_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('WITHIN_TOLERANCE', 'Within Tolerance'), ('WATCH', 'Watch'), ('OVER_TOLERANCE', 'Over Tolerance'), ('NOT_CALCULATED', 'Not Calculated')], db_index=True, default='NOT_CALCULATED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_entries', to='reconciliation.item')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reconciliation Entry',
                'verbose_name_plural': 'Reconciliation Entries',
                'db_table': 'reconciliation_entry',
                'ordering': ['item__item_name'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('period_month', models.DateField(help_text='Normalized to the first day of the month.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=20)),
                ('tolerance_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Overrides the global default tolerance for this period only.', max_digits=5, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_records', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_periods', to='organization.site')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reconciliation_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reconciliation Period',
                'verbose_name_plural': 'Reconciliation Periods',
                'db_table': 'reconciliation_period',
                'ordering': ['-period_month', 'site__site_name'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationOutputEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade_label', models.CharField(blank=True, max_length=50)),
                ('output_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_output_entries', to='reconciliation.item')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_entries', to='reconciliation.reconciliationperiod')),
            ],
            options={
                'verbose_name': 'Reconciliation Output Entry',
                'verbose_name_plural': 'Reconciliation Output Entries',
                'db_table': 'reconciliation_output_entry',
                'ordering': ['item__item_name'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flag_type', models.CharField(choices=[('NEGATIVE_CONSUMPTION', 'Negative Consumption'), ('NO_MATCHING_PRODUCTION', 'No Matching Production'), ('MISSING_MIX_OR_RATE', 'Missing Mix Ratio Or Rate'), ('OVER_TOLERANCE', 'Over Tolerance')], db_index=True, max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='reconciliation.reconciliationentry')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flags', to='reconciliation.reconciliationperiod')),
            ],
            options={
                'verbose_name': 'Reconciliation Flag',
                'verbose_name_plural': 'Reconciliation Flags',
                'db_table': 'reconciliation_flag',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='reconciliationentry',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='reconciliation.reconciliationperiod'),
        ),
        migrations.AddIndex(
            model_name='reconciliationperiod',
            index=models.Index(fields=['site', 'status'], name='reco_period_site_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationperiod',
            index=models.Index(fields=['period_month', 'status'], name='reco_period_month_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('site', 'period_month'), name='reco_period_site_month_uniq'),
        ),
        migrations.AddIndex(
            model_name='reconciliationoutputentry',
            index=models.Index(fields=['period', 'item'], name='reco_output_period_item_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationflag',
            index=models.Index(fields=['period', 'flag_type'], name='reco_flag_period_type_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationflag',
            index=models.Index(fields=['entry', 'flag_type'], name='reco_flag_entry_type_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationentry',
            index=models.Index(fields=['period', 'status'], name='reco_entry_period_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationentry',
            constraint=models.UniqueConstraint(fields=('period', 'item'), name='reco_entry_period_item_uniq'),
        ),
    ]
