# Generated by Django 5.2.15 on 2026-08-24 10:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0002_reconciliationtolerancesettings_reconciliationentry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round_number', models.PositiveSmallIntegerField(default=1)),
                ('sequence', models.PositiveSmallIntegerField(db_index=True)),
                ('level_name', models.CharField(blank=True, max_length=120)),
                ('approver_type', models.CharField(choices=[('STORE_HO', 'Store HO'), ('DIRECTOR', 'Director'), ('ADMIN_FINAL', 'Admin Final Approval'), ('CUSTOM', 'Custom Approver')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned For Clarification'), ('DELEGATED', 'Delegated'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=30)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('approver_employee_id_snapshot', models.CharField(blank=True, max_length=30)),
                ('approver_name_snapshot', models.CharField(blank=True, max_length=150)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_approval_steps', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_steps', to='reconciliation.reconciliationperiod')),
            ],
            options={
                'verbose_name': 'Reconciliation Approval Step',
                'verbose_name_plural': 'Reconciliation Approval Steps',
                'db_table': 'reconciliation_approval_step',
                'ordering': ['period', 'round_number', 'sequence'],
                'indexes': [models.Index(fields=['period', 'status'], name='reco_step_period_status_idx'), models.Index(fields=['approver', 'status'], name='reco_step_approver_status_idx'), models.Index(fields=['period', 'is_current'], name='reco_step_period_current_idx')],
                'constraints': [models.UniqueConstraint(fields=('period', 'round_number', 'sequence'), name='reco_approval_step_period_round_seq_uniq')],
            },
        ),
    ]
