# Generated by Django 5.2.15 on 2026-08-24 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_alter_site_site_hod'),
        ('reconciliation', '0003_reconciliationapprovalstep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemstandard',
            options={'ordering': ['item__item_name', 'grade_label', '-effective_from'], 'verbose_name': 'Item Standard (Company Default)', 'verbose_name_plural': 'Item Standards (Company Defaults)'},
        ),
        migrations.AlterModelOptions(
            name='siteitemconfig',
            options={'ordering': ['site__site_name', 'item__item_name', 'grade_label', '-effective_from'], 'verbose_name': 'Site Item Configuration', 'verbose_name_plural': 'Site Item Configurations'},
        ),
        migrations.RemoveConstraint(
            model_name='itemstandard',
            name='reco_item_standard_item_date_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='siteitemconfig',
            name='reco_site_item_date_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='siteitemconfig',
            name='reco_site_item_active_uniq',
        ),
        migrations.AddField(
            model_name='itemstandard',
            name='grade_label',
            field=models.CharField(blank=True, help_text='Leave blank to apply to every production grade of this item. Set to override the mix ratio (and rate) for one specific grade only, e.g. M20 - must match the grade recorded on production output.', max_length=50),
        ),
        migrations.AddField(
            model_name='siteitemconfig',
            name='grade_label',
            field=models.CharField(blank=True, help_text='Leave blank to apply to every production grade of this item at this site. Set to override the mix ratio (and rate) for one specific grade only.', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='itemstandard',
            constraint=models.UniqueConstraint(fields=('item', 'grade_label', 'effective_from'), name='reco_item_standard_item_grade_date_uniq'),
        ),
        migrations.AddConstraint(
            model_name='siteitemconfig',
            constraint=models.UniqueConstraint(fields=('item', 'site', 'grade_label', 'effective_from'), name='reco_site_item_grade_date_uniq'),
        ),
        migrations.AddConstraint(
            model_name='siteitemconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('item', 'site', 'grade_label'), name='reco_site_item_grade_active_uniq'),
        ),
    ]
