# Generated by Django 5.2.15 on 2026-08-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0004_alter_itemstandard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationentry',
            name='rack',
            field=models.CharField(blank=True, help_text='Rack / bin location within the section. Optional, informational only.', max_length=100),
        ),
        migrations.AddField(
            model_name='reconciliationentry',
            name='resolved_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Rate used to cost this entry's variance, snapshotted whenever the variance is recomputed - shown on the printed statement.", max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationentry',
            name='section',
            field=models.CharField(blank=True, help_text='Physical storage section for this item at the site, e.g. Section A. Optional, informational only.', max_length=100),
        ),
    ]
