# Generated by Django 5.2.15 on 2026-08-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0005_reconciliationentry_rack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationperiod',
            name='closing_stock_date',
            field=models.DateField(blank=True, help_text='The date the closing physical stock count was taken, if recorded.', null=True),
        ),
        migrations.AddField(
            model_name='reconciliationperiod',
            name='opening_stock_date',
            field=models.DateField(blank=True, help_text='The date the opening physical stock count was taken, if recorded. Informational only - printed on the statement, not used in the calculation.', null=True),
        ),
    ]
