# Generated by Django 5.2.15 on 2026-08-27 08:14

import apps.reconciliation.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0006_reconciliationperiod_closing_stock_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationPeriodAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to=apps.reconciliation.models.reconciliation_attachment_upload_to)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_records', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='reconciliation.reconciliationperiod')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reconciliation Period Attachment',
                'verbose_name_plural': 'Reconciliation Period Attachments',
                'db_table': 'reconciliation_period_attachment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['period', 'is_deleted'], name='reco_attach_period_del_idx')],
            },
        ),
    ]
