# Generated by Django 5.2.15 on 2026-08-27 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_alter_site_site_hod'),
        ('reconciliation', '0007_reconciliationperiodattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='siteitemconfig',
            name='reco_site_item_grade_date_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='siteitemconfig',
            name='reco_site_item_grade_active_uniq',
        ),
        migrations.AddField(
            model_name='siteitemconfig',
            name='period',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a standing site override. Set to a specific period to override the rate/mix for that one month only, on top of the standing site override.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_item_overrides', to='reconciliation.reconciliationperiod'),
        ),
        migrations.AddConstraint(
            model_name='siteitemconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('period__isnull', True)), fields=('item', 'site', 'grade_label', 'effective_from'), name='reco_site_item_grade_date_uniq'),
        ),
        migrations.AddConstraint(
            model_name='siteitemconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('period__isnull', True)), fields=('item', 'site', 'grade_label'), name='reco_site_item_grade_active_uniq'),
        ),
        migrations.AddConstraint(
            model_name='siteitemconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('period__isnull', False)), fields=('item', 'site', 'grade_label', 'period'), name='reco_site_item_grade_period_active_uniq'),
        ),
    ]
