# Generated by Django 5.2.15 on 2026-08-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0008_remove_siteitemconfig_reco_site_item_grade_date_uniq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_production_output',
            field=models.BooleanField(default=False, help_text="This item is something produced (e.g. Concrete), not a raw material consumed to make it. Only production-output items appear on the Production Output entry form; every other item is a material reconciled against opening/receipts/closing (or book/physical count) as usual - its theoretical consumption is derived from whichever production-output batches were logged for the period, using this item's own mix ratio for each grade produced."),
        ),
    ]
