# Generated by Django 5.2.15 on 2026-08-31 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0009_item_is_production_output'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reconciliationoutputentry',
            options={'ordering': ['category__category_name'], 'verbose_name': 'Reconciliation Output Entry', 'verbose_name_plural': 'Reconciliation Output Entries'},
        ),
        migrations.RemoveIndex(
            model_name='reconciliationoutputentry',
            name='reco_output_period_item_idx',
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='is_production_output',
            field=models.BooleanField(default=False, help_text='This is a production type (e.g. Concrete) - every item assigned to it is one of its recipe materials, and it becomes selectable as a product on Production Output.'),
        ),
        migrations.AddField(
            model_name='reconciliationoutputentry',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_output_entries', to='reconciliation.itemcategory'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_production_output',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reconciliationoutputentry',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_output_entries_old', to='reconciliation.item'),
        ),
        migrations.AddIndex(
            model_name='reconciliationoutputentry',
            index=models.Index(fields=['period', 'category'], name='reco_output_period_cat_idx'),
        ),
    ]
