# Generated by Django 5.2.15 on 2026-08-31 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0011_backfill_output_entry_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_production_output',
        ),
        migrations.RemoveField(
            model_name='reconciliationoutputentry',
            name='item',
        ),
        migrations.AlterField(
            model_name='reconciliationoutputentry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_output_entries', to='reconciliation.itemcategory'),
        ),
    ]
