# Generated by Django 5.2.15 on 2026-08-31 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0012_finalize_category_production_output'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reconciliationentry',
            name='reco_entry_period_item_uniq',
        ),
        migrations.AddField(
            model_name='reconciliationentry',
            name='grade_label',
            field=models.CharField(blank=True, help_text="Which production grade this material's actual consumption is for (e.g. M20) - blank for a material not tied to a specific grade's output batch, or for a material with no recipe at all. A norm-based item can have one entry per grade produced this period.", max_length=50),
        ),
        migrations.AddConstraint(
            model_name='reconciliationentry',
            constraint=models.UniqueConstraint(fields=('period', 'item', 'grade_label'), name='reco_entry_period_item_grade_uniq'),
        ),
    ]
