# Generated by Django 5.2.15 on 2026-08-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0013_remove_reconciliationentry_reco_entry_period_item_uniq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationentry',
            name='grade_label',
            field=models.CharField(blank=True, default='', help_text="Which production grade this material's actual consumption is for (e.g. M20) - blank for a material not tied to a specific grade's output batch, or for a material with no recipe at all. A norm-based item can have one entry per grade produced this period.", max_length=50),
        ),
    ]
