# Generated by Django 5.2.15 on 2026-09-01 05:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0014_alter_reconciliationentry_grade_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategoryGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade_label', models.CharField(max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='reconciliation.itemcategory')),
            ],
            options={
                'verbose_name': 'Item Category Grade',
                'verbose_name_plural': 'Item Category Grades',
                'db_table': 'reconciliation_item_category_grade',
                'ordering': ['display_order', 'grade_label'],
                'constraints': [models.UniqueConstraint(fields=('category', 'grade_label'), name='reco_cat_grade_uniq')],
            },
        ),
    ]
