# Generated by Django 5.2.15 on 2026-09-10 05:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0020_merge_grade_split_reconciliation_entries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reconciliationentry',
            name='reco_entry_period_item_grade_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='reconciliationentry',
            name='reco_entry_period_item_cat_grade_uniq',
        ),
        migrations.RemoveField(
            model_name='reconciliationentry',
            name='category',
        ),
        migrations.RemoveField(
            model_name='reconciliationentry',
            name='grade_label',
        ),
        migrations.AddConstraint(
            model_name='reconciliationentry',
            constraint=models.UniqueConstraint(fields=('period', 'item'), name='reco_entry_period_item_uniq'),
        ),
    ]
