# Generated by Django 5.2.15 on 2026-09-24 04:48

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0021_drop_reconciliation_entry_grade_and_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationentry',
            name='miscellaneous_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text="Quantity of this material consumed on non-production work this month (see ReconciliationMiscUsage), snapshotted whenever the variance is recomputed. It is deducted from the month's consumption before variance is worked out. Not entered here.", max_digits=14),
        ),
        migrations.CreateModel(
            name='ReconciliationMiscUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='misc_usages', to='reconciliation.item')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='misc_usages', to='reconciliation.reconciliationperiod')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reconciliation Miscellaneous Use',
                'verbose_name_plural': 'Reconciliation Miscellaneous Use',
                'db_table': 'reconciliation_misc_usage',
                'ordering': ['item__item_name'],
                'constraints': [models.UniqueConstraint(fields=('period', 'item'), name='reco_misc_period_item_uniq', violation_error_message='This material already has a miscellaneous use entry for this period - edit it instead of adding another.')],
            },
        ),
    ]
